version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: awsyandex
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  com-artem:
    image: com-artem:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:

      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/awsyandex
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/awsyandex
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      # AWS настройки
      ARTEM_AWS_ACCESS_KEY: add
      ARTEM_AWS_SECRET_KEY: add
      ARTEM_AWS_REGION: ru-central1
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:





































