server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:pool:postgres://postgres:5432/awsyandex
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://postgres:5432/awsyandex
    locations: classpath:db/migration
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: artem


yandex:
  cloud:
    access-key: add new
    secret-key: add new
    region: ru-central1
    endpoint: https://storage.yandexcloud.net
    bucket: spring-boot-s3example





































